# Transformers, what can they do?

Install the Transformers, Datasets, and Evaluate libraries to run this notebook.

In [ ]:
!pip install datasets evaluate transformers[sentencepiece]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 431 kB 26.7 MB/s 
     |████████████████████████████████| 69 kB 8.3 MB/s 
     |████████████████████████████████| 4.9 MB 67.1 MB/s 
     |████████████████████████████████| 212 kB 67.8 MB/s 
     |████████████████████████████████| 163 kB 66.4 MB/s 
     |████████████████████████████████| 115 kB 56.0 MB/s 
     |████████████████████████████████| 127 kB 73.0 MB/s 
     |████████████████████████████████| 6.6 MB 46.3 MB/s 
     |████████████████████████████████| 1.3 MB 76.9 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3


In [ ]:
from transformers import pipeline

classifier = pipeline(task="sentiment-analysis")
classifier("I've been waiting for a HuggingFace course my whole life.")

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


Downloading:   0%|          | 0.00/629 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/268M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

[{'label': 'POSITIVE', 'score': 0.9598049521446228}]

In [ ]:
classifier(
    ["I've been waiting for a HuggingFace course my whole life.", "I hate this so much!"]
)

[{'label': 'POSITIVE', 'score': 0.9598047137260437},
 {'label': 'NEGATIVE', 'score': 0.9994558095932007}]

In [ ]:
classifier(
    ["I've been waiting for a HuggingFace course my whole life."])[0]["label"]


'POSITIVE'

In [ ]:
y_pred =[]
for i in ["I've been waiting for a HuggingFace course my whole life.", "I hate this so much!"]:
  if classifier(i)[0]["label"] == "POSITIVE":
    y_pred.append(0)
  else:
    y_pred.append(1)
y_pred

[0, 1]

In [ ]:
from transformers import pipeline

classifier = pipeline("zero-shot-classification")
classifier(
    "This is a course about the Transformers library",
    candidate_labels=["education", "politics", "business"],
)

No model was supplied, defaulted to facebook/bart-large-mnli and revision c626438 (https://huggingface.co/facebook/bart-large-mnli).
Using a pipeline without specifying a model name and revision in production is not recommended.


Downloading:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/899k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

{'sequence': 'This is a course about the Transformers library',
 'labels': ['education', 'business', 'politics'],
 'scores': [0.8445985913276672, 0.11197461187839508, 0.04342680424451828]}

In [ ]:
classifier(
    "This is a course about the Transformers library",
    candidate_labels=["human", "teach", "art","sport"],
)

{'sequence': 'This is a course about the Transformers library',
 'labels': ['teach', 'art', 'sport', 'human'],
 'scores': [0.9819722175598145,
  0.007555442862212658,
  0.005879631265997887,
  0.004592622630298138]}

In [ ]:
classifier(
    ["world cup will be held in qatar this year", "ballet and theater are indispensable for me.", "This year, a new law on animal rights was enacted."],
    candidate_labels=["education", "politics", "business", "art", "sport", "justice"],
)

[{'sequence': 'world cup will be held in qatar this year',
  'labels': ['sport', 'politics', 'business', 'justice', 'art', 'education'],
  'scores': [0.8783334493637085,
   0.04051613435149193,
   0.03470348194241524,
   0.01913808286190033,
   0.017712391912937164,
   0.009596414864063263]},
 {'sequence': 'ballet and theater are indispensable for me.',
  'labels': ['art', 'justice', 'sport', 'business', 'education', 'politics'],
  'scores': [0.9215366840362549,
   0.03311394527554512,
   0.023203646764159203,
   0.009502392262220383,
   0.009387074038386345,
   0.0032561784610152245]},
 {'sequence': 'This year, a new law on animal rights was enacted.',
  'labels': ['justice', 'sport', 'business', 'politics', 'art', 'education'],
  'scores': [0.572504997253418,
   0.14231139421463013,
   0.08730414509773254,
   0.0830569863319397,
   0.06940555572509766,
   0.04541695863008499]}]

In [ ]:
from transformers import pipeline

generator = pipeline("text-generation")
generator("In this course, we will teach you how to")

No model was supplied, defaulted to gpt2 and revision 6c0e608 (https://huggingface.co/gpt2).
Using a pipeline without specifying a model name and revision in production is not recommended.


Downloading:   0%|          | 0.00/665 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/548M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
/usr/local/lib/python3.7/dist-packages/transformers/generation_utils.py:1232: UserWarning: Neither `max_length` nor `max_new_tokens` has been set, `max_length` will default to 50 (`self.config.max_length`). Controlling `max_length` via the config is deprecated and `max_length` will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  UserWarning,


[{'generated_text': 'In this course, we will teach you how to take the necessary steps to set up Google Chrome.\n\nGetting access to the Web page that you are looking for (or looking for if you are visiting a website)\n\nIf you search for'}]

In [ ]:
from transformers import pipeline

generator = pipeline("text-generation", model="distilgpt2")
generator(
    "In this course, we will teach you how to",
    max_length=30,
    num_return_sequences=2,
)

Downloading:   0%|          | 0.00/762 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/353M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'In this course, we will teach you how to use the NBT to connect your own devices to the internet. I also promise you that all computers'},
 {'generated_text': 'In this course, we will teach you how to make your own money. For a full course, I suggest starting with a $500-400 contribution'}]

In [ ]:
from transformers import pipeline

unmasker = pipeline("fill-mask")
unmasker("This course will teach you all about <mask> models.", top_k=2)

No model was supplied, defaulted to distilroberta-base and revision ec58a5b (https://huggingface.co/distilroberta-base).
Using a pipeline without specifying a model name and revision in production is not recommended.


Downloading:   0%|          | 0.00/480 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/331M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/899k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

[{'score': 0.19619761407375336,
  'token': 30412,
  'token_str': ' mathematical',
  'sequence': 'This course will teach you all about mathematical models.'},
 {'score': 0.04052722454071045,
  'token': 38163,
  'token_str': ' computational',
  'sequence': 'This course will teach you all about computational models.'}]

In [ ]:
from transformers import pipeline

ner = pipeline("ner", grouped_entities=True)
ner("My name is Sylvain and I work at Hugging Face in Brooklyn.")

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision f2482bf (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


Downloading:   0%|          | 0.00/998 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]

/usr/local/lib/python3.7/dist-packages/transformers/pipelines/token_classification.py:136: UserWarning: `grouped_entities` is deprecated and will be removed in version v5.0.0, defaulted to `aggregation_strategy="simple"` instead.
  "`grouped_entities` is deprecated and will be removed in version v5.0.0, defaulted to"


[{'entity_group': 'PER',
  'score': 0.9981694,
  'word': 'Sylvain',
  'start': 11,
  'end': 18},
 {'entity_group': 'ORG',
  'score': 0.97960204,
  'word': 'Hugging Face',
  'start': 33,
  'end': 45},
 {'entity_group': 'LOC',
  'score': 0.9932106,
  'word': 'Brooklyn',
  'start': 49,
  'end': 57}]

In [ ]:
from transformers import pipeline

ner = pipeline("ner")
ner("My name is Sylvain and I work at Hugging Face in Brooklyn.")

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision f2482bf (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


[{'entity': 'I-PER',
  'score': 0.99938285,
  'index': 4,
  'word': 'S',
  'start': 11,
  'end': 12},
 {'entity': 'I-PER',
  'score': 0.99815494,
  'index': 5,
  'word': '##yl',
  'start': 12,
  'end': 14},
 {'entity': 'I-PER',
  'score': 0.99590707,
  'index': 6,
  'word': '##va',
  'start': 14,
  'end': 16},
 {'entity': 'I-PER',
  'score': 0.99923277,
  'index': 7,
  'word': '##in',
  'start': 16,
  'end': 18},
 {'entity': 'I-ORG',
  'score': 0.97389334,
  'index': 12,
  'word': 'Hu',
  'start': 33,
  'end': 35},
 {'entity': 'I-ORG',
  'score': 0.976115,
  'index': 13,
  'word': '##gging',
  'start': 35,
  'end': 40},
 {'entity': 'I-ORG',
  'score': 0.9887976,
  'index': 14,
  'word': 'Face',
  'start': 41,
  'end': 45},
 {'entity': 'I-LOC',
  'score': 0.9932106,
  'index': 16,
  'word': 'Brooklyn',
  'start': 49,
  'end': 57}]

In [ ]:
from transformers import pipeline

question_answerer = pipeline("question-answering")
question_answerer(
    question="Where do I work?",
    context="My name is Sylvain and I work at Hugging Face in Brooklyn",
)

No model was supplied, defaulted to distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


Downloading:   0%|          | 0.00/473 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/261M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/436k [00:00<?, ?B/s]

{'score': 0.6949767470359802, 'start': 33, 'end': 45, 'answer': 'Hugging Face'}

In [ ]:
question_answerer(
    question=["Where do you work?", "In which city do you work?", "what is your name"],
    context="My name is Sylvain and I work at Hugging Face in Brooklyn",
)

[{'score': 0.7144076824188232,
  'start': 33,
  'end': 45,
  'answer': 'Hugging Face'},
 {'score': 0.8743698000907898, 'start': 49, 'end': 57, 'answer': 'Brooklyn'},
 {'score': 0.990521252155304, 'start': 11, 'end': 18, 'answer': 'Sylvain'}]

In [ ]:
from transformers import pipeline

summarizer = pipeline("summarization")
summarizer(
    """
    America has changed dramatically during recent years. Not only has the number of 
    graduates in traditional engineering disciplines such as mechanical, civil, 
    electrical, chemical, and aeronautical engineering declined, but in most of 
    the premier American universities engineering curricula now concentrate on 
    and encourage largely the study of engineering science. As a result, there 
    are declining offerings in engineering subjects dealing with infrastructure, 
    the environment, and related issues, and greater concentration on high 
    technology subjects, largely supporting increasingly complex scientific 
    developments. While the latter is important, it should not be at the expense 
    of more traditional engineering.

    Rapidly developing economies such as China and India, as well as other 
    industrial countries in Europe and Asia, continue to encourage and advance 
    the teaching of engineering. Both China and India, respectively, graduate 
    six and eight times as many traditional engineers as does the United States. 
    Other industrial countries at minimum maintain their output, while America 
    suffers an increasingly serious decline in the number of engineering graduates 
    and a lack of well-educated engineers.
"""
)

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.


Downloading:   0%|          | 0.00/1.80k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/899k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

[{'summary_text': ' America has changed dramatically during recent years . The number of engineering graduates in the U.S. has declined in traditional engineering disciplines such as mechanical, civil,    electrical, chemical, and aeronautical engineering . Rapidly developing economies such as China and India continue to encourage and advance the teaching of engineering .'}]

In [ ]:
from transformers import pipeline

translator = pipeline("translation", model="Helsinki-NLP/opus-mt-fr-en")
translator("Ce cours est produit par Hugging Face.")

Downloading:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/301M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/802k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/778k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.34M [00:00<?, ?B/s]

/usr/local/lib/python3.7/dist-packages/transformers/models/marian/tokenization_marian.py:194: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")


[{'translation_text': 'This course is produced by Hugging Face.'}]

In [ ]:
from transformers import pipeline
question_answers =pipeline(task='question-answering', model='deepset/roberta-base-squad2')
question_answerer(
    question="Which team beat real madrid?",
    context="Barcelona became champion of Spain after beating Real Madrid",
)


Downloading:   0%|          | 0.00/571 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/496M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/79.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/899k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/772 [00:00<?, ?B/s]

{'score': 0.5713405013084412, 'start': 0, 'end': 9, 'answer': 'Barcelona'}

In [ ]:
translation =pipeline(task='translation', model = 'Helsinki-NLP/opus-mt-tr-en')

translation('Ben kugu dansina bayilirim')

Downloading:   0%|          | 0.00/1.38k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/307M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/840k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/797k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.56M [00:00<?, ?B/s]

/usr/local/lib/python3.7/dist-packages/transformers/models/marian/tokenization_marian.py:194: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")


[{'translation_text': 'I love cug dancing.'}]

In [ ]:
from transformers import pipeline
classifier = pipeline("zero-shot-classification", model="MoritzLaurer/mDeBERTa-v3-base-mnli-xnli")


classifier(
    ["Galatasaray bu sene şampiyonlar ligine katılacak", "Savaş sonrası enflasyon arttı"],
    candidate_labels=["spor", "siyaset", "ekonomi", "sanat"],
)

Downloading:   0%|          | 0.00/1.07k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/558M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/463 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/18.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/156 [00:00<?, ?B/s]

/usr/local/lib/python3.7/dist-packages/transformers/convert_slow_tokenizer.py:447: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  "The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option"
/usr/local/lib/python3.7/dist-packages/transformers/models/deberta_v2/modeling_deberta_v2.py:746: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  scale, dtype=query_layer.dtype
/usr/local/lib/python3.7/dist-packages/transformers/models/deberta_v2/modeling_deberta_

[{'sequence': 'Galatasaray bu sene şampiyonlar ligine katılacak',
  'labels': ['spor', 'siyaset', 'sanat', 'ekonomi'],
  'scores': [0.7193388938903809,
   0.14446769654750824,
   0.06898367404937744,
   0.06720971316099167]},
 {'sequence': 'Savaş sonrası enflasyon arttı',
  'labels': ['ekonomi', 'siyaset', 'sanat', 'spor'],
  'scores': [0.8702477216720581,
   0.10678886622190475,
   0.012205569073557854,
   0.010757893323898315]}]

In [ ]:
unmasker = pipeline("fill-mask", model="bert-base-uncased")
unmasker("Galatasaray [MASK] Fenerbahce 5-0.", top_k=2)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


[{'score': 0.4796569347381592,
  'token': 3249,
  'token_str': 'defeated',
  'sequence': 'galatasaray defeated fenerbahce 5 - 0.'},
 {'score': 0.44297853112220764,
  'token': 3786,
  'token_str': 'beat',
  'sequence': 'galatasaray beat fenerbahce 5 - 0.'}]

In [ ]:
unmasker = pipeline("fill-mask", model="bert-base-uncased")
unmasker("Fenerbahce [MASK] 5-0 to Galatasaray", top_k=2)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


[{'score': 0.8901094794273376,
  'token': 2439,
  'token_str': 'lost',
  'sequence': 'fenerbahce lost 5 - 0 to galatasaray'},
 {'score': 0.048826541751623154,
  'token': 4558,
  'token_str': 'lose',
  'sequence': 'fenerbahce lose 5 - 0 to galatasaray'}]

In [ ]:
pip install -U sentence-transformers


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 85 kB 4.0 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=ee4bd4a516945ce3fcbe6cefb0b97c9df4acc78c3e9fdea00bd46b5d3f7d8f19
  Stored in directory: /root/.cache/pip/wheels/bf/06/fb/d59c1e5bd1dac7f6cf61ec0036cc3a10ab8fecaa6b2c3d3ee9
Successfully built sentence-transformers


In [ ]:
from sentence_transformers import SentenceTransformer
sentences = ["This is an example sentence", "Each sentence is converted", "Let me give you an example from the sentence"]

model = SentenceTransformer('sentence-transformers/bert-base-nli-mean-tokens')
embeddings = model.encode(sentences)
print(embeddings)


Downloading:   0%|          | 0.00/391 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.95k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/122 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/399 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

[[-0.39310005  0.03886264  1.9874239  ... -0.6093679  -1.0946207
   0.32649064]
 [ 0.06153341  0.32736215  1.833232   ... -0.12985356  0.46089387
   0.24035425]
 [ 0.03920036 -0.08954653  2.0578127  ... -0.11227314 -0.9744803
   0.11509919]]


In [ ]:
embeddings[0]

array([-3.93100053e-01,  3.88626382e-02,  1.98742390e+00, -1.36893526e-01,
        1.93089530e-01,  3.74967605e-01,  1.15455195e-01,  3.02821577e-01,
        2.32356653e-01, -1.23267971e-01, -2.69240946e-01,  4.10017669e-01,
       -2.14588195e-01,  1.45402029e-01,  4.17345285e-01, -2.67233521e-01,
       -2.92259514e-01, -1.81810141e-01,  9.90739822e-01, -7.87549317e-01,
       -7.95890167e-02,  7.74835587e-01, -3.67454439e-01, -1.04439950e+00,
        3.26537907e-01, -8.63254845e-01,  3.20690453e-01, -1.12830329e+00,
       -4.59388793e-01, -4.49143909e-02,  6.30563051e-02, -6.13952994e-01,
        3.75282079e-01, -1.02702618e-01,  8.16330984e-02,  2.59928584e-01,
        4.26196754e-01, -1.09225744e-02,  1.49220541e-01,  2.61052936e-01,
        8.91624033e-01, -5.76651156e-01,  9.52781081e-01,  1.79338351e-01,
       -9.76019681e-01, -6.75556183e-01, -7.54613578e-01,  3.20075095e-01,
       -3.51042271e-01, -7.56071448e-01, -1.71005225e+00,  3.14682215e-01,
        3.91978413e-01,  

In [ ]:
len(embeddings[0])

768

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
cosine_similarity([embeddings[0]], embeddings[1:])

array([[0.57836944, 0.8971245 ]], dtype=float32)

In [ ]:
sentences = ["How old are you?", "What is your age?", "How old do I show?"]
embeddings = model.encode(sentences)
cosine_similarity([embeddings[0]], embeddings[1:])

array([[0.8182197, 0.9400088]], dtype=float32)

In [ ]:
sentences = ["cat", "dog", "house"]
embeddings = model.encode(sentences)
cosine_similarity([embeddings[0]], embeddings[1:])

array([[0.23537235, 0.56530607]], dtype=float32)

In [ ]:
sentences = ["cat", "kitten", "house"]
embeddings = model.encode(sentences)
cosine_similarity([embeddings[0]], embeddings[1:])

array([[0.8424369, 0.5653061]], dtype=float32)

In [ ]:
sentences = ["car", "auto", "sport car"]
embeddings = model.encode(sentences)
cosine_similarity([embeddings[0]], embeddings[1:])

array([[0.77519256, 0.8565937 ]], dtype=float32)

In [ ]:
sentences = ["car", "auto", "sport"]
embeddings = model.encode(sentences)
cosine_similarity([embeddings[0]], embeddings[1:])

array([[0.77519256, 0.497505  ]], dtype=float32)